name: CI/CD Pipeline

on:
  push: # Run workflow on push to the master branch
    branches:
      - master

  pull_request:  # Run workflow on pull requests targeting the master branch
    branches:
      - master

jobs:
  test:  # Test job
    runs-on: ubuntu-latest   # Run on the latest Ubuntu environment

    steps:
      - name: Checkout code  
        uses: actions/checkout@v2   # Checkout the repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # Install Docker Compose

      - name: Ensure Docker Compose is available
        run: docker-compose version  # Verify Docker Compose installation

      - name: Copy .env.example to .env  # Copy the .env.example to .env
        run: cp integration-test/.env.example integration-test/.env

      - name: Grant execute permissions to the integration script
        run: chmod +x integration-test/scripts/run-integration.sh  # Grant execute permissions to the script

      - name: Run integration script
        run: cd integration-test && npm run test:integration  # Change directory and run integration tests
