name: CI/CD Pipeline

on:
  push: #any time there is push on main branch this ci/cd pipe line will execute
    branches:
      - master
 
  pull_request:  #any time there is pull on main branch this ci/cd pipe line will execute
    branches:
      - master


jobs:
  test:  #test jobs
    runs-on: ubuntu-latest   #run on ubuntu

    steps:
    - name: Checkout code  
      uses: actions/checkout@v2   #checkout the code usig this

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2    #check docker is install or not

    - name: Set up Docker Compose
      uses: docker/setup-qemu-action@v2  #is there docker compose actually there

    - name: Ensure Docker Compose is available
      run: docker-compose version

    - name: Copy .env.example to .env  #copy the .env.example to .env
      run: cp integration-test/.env.example ./integration-test/.env

    - name: Run integration script
      run: cd integration-test && npm run test:integration      #cd  folder then run this test and in json where test is declare
